Add resolution information to the camera model
tue-robotics/rgbd pull request #44
Opened 2021-10-29 19:53 UTC by PetervDooren

Noticed that when I deserialised an rgbd file the fullresolution parameter of the camera model was empty

2021-10-31 16:32 UTC, MatthijsBurgh commented on rgbd/src/serialization.cpp
> +        // now that the image size is known add it to the camera model
This suggest that somewhere earlier in the code there is a comment that we don't know the resolution yet. That comment is missing.

2021-10-31 16:32 UTC, MatthijsBurgh requested changes
See comment about comment ;)

2021-11-05 11:26 UTC, MatthijsBurgh commented
The [camera_info](http://docs.ros.org/en/noetic/api/sensor_msgs/html/msg/CameraInfo.html) message, does contain, the width and heigth. So I would like to figure out we could integrate that here. Or that we don't have that info, when (de)serializing the message in the current flow.

2021-11-05 13:33 UTC, PetervDooren commented
The problem here is (I think). That there are multiple ways in which the image can be encoded. So you cannot create a flow where this info is extracted before the rgb is processed (or depth, depends on which one you use, assumed now is that they use the same camera model.)
And while the camera_info message does contain this information, the cam_info message is used as an intermediary in this process, so it does not contain information that we did not put in

2021-11-05 14:48 UTC, MatthijsBurgh commented
Indeed, it contains only the info that we put in.

The question is: Do we not have the info when serializing it, so we can't put it in. Or do we have the info, but we just neglect to add it..

2021-11-05 14:50 UTC, PetervDooren commented
The info is added, just not near the other camera info if I recall

2021-11-09 23:30 UTC, MatthijsBurgh commented
As discussed, we could look into adding the info on more places.

2021-11-10 08:24 UTC, PetervDooren commented
The discussed method is applied in #45

2021-11-10 08:24 UTC, closed without merging